version: "3.8"

services:
  app:
    container_name: todo_app_dev
    build:
      context: .
      dockerfile: Dockerfile.development
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file: ./.env.development
    ports:
      - 5000:5000
    environment:
      - MYSQL_HOST     = $MYSQL_DATABASE
      - MYSQL_USER     = $MYSQL_USER
      - MYSQL_PASSWORD = $MYSQL_PASSWORD
      - MYSQL_DATABASE = $MYSQL_DATABASE
    network_mode: host
