version: "3.8"

services:
  app:
    container_name: todo_app_dev
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    env_file: ./.env.development
    ports:
      - $NODE_PORT:5000
    environment:
      - MYSQL_HOST     = $MYSQL_DATABASE
      - MYSQL_USER     = $MYSQL_USER
      - MYSQL_PASSWORD = $MYSQL_PASSWORD
      - MYSQL_DATABASE = $MYSQL_DATABASE
