FROM node:alpine as builder

WORKDIR /usr/src/app
COPY package*.json .
RUN npm install
COPY ./ ./

RUN npm run build

FROM node:alpine as staging

WORKDIR /usr/src/app
COPY package*.json .
RUN npm ci --omit=dev
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 5000

CMD [ "npm", "run", "start:staging" ]