name: Deploy Node.js App to ECR - Staging

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # Check the Dockerfile to build the docker image
      - name: Checkout code
        uses: actions/checkout@v3

      # Programmatic authentication to aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: todo_node
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.staging .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
